const productos = [
    {
        id: "buso-01",
        titulo: "Buso DC",
        imagen: "./img/buzo01.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "buso-02",
        titulo: "Buso Volcom",
        imagen: "./img/buzo02.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "buso-03",
        titulo: "Buso Vulk",
        imagen: "./img/buzo03.jpg",
       precio: 1000,
        cantidad: 1,
    },
    {
        id: "buso-04",
        titulo: "Buso Independt",
        imagen: "./img/buzo04.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "buso-05",
        titulo: "Buso Creature",
        imagen: "./img/buzo05.jpg",
       precio: 1000,
        cantidad: 1,
    },
    {
        id: "buso-06",
        titulo: "Buso Thrasher",
        imagen: "./img/buzo06.jpg",
       precio: 1000,
        cantidad: 1,
    },
    {
        id: "buso-07",
        titulo: "Buso Vans",
        imagen: "./img/buzo07.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "buso-08",
        titulo: "Buso Independt",
        imagen: "./img/buzo08.jpg",
        precio: 1000,
        cantidad: 1,
    },

    // REMERAS 
    {
        id: "remera-01",
        titulo: "Remera Sarter",
        imagen: "./img/remera01.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "remera-02",
        titulo: "Remera Sarter",
        imagen: "./img/remera02.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "remera-03",
        titulo: "Remera Element",
        imagen: "./img/remera03.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "remera-04",
        titulo: "Remera Santa Cruz",
        imagen: "./img/remera04.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "remera-05",
        titulo: "Remera Creature",
        imagen: "./img/remera05.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "remera-06",
        titulo: "Remera Independt",
        imagen: "./img/remera06.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "remera-07",
        titulo: "Remera Vans",
        imagen: "./img/remera07.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "remera-08",
        titulo: "Musculosa Volcom",
        imagen: "./img/remera08.jpg",
       precio: 1000,
        cantidad: 1,
    },

    // accesorios 
    {
        id: "accesorio-01",
        titulo: "Truck Krux",
        imagen: "./img/truck01.jpg",
       precio: 1000,
        cantidad: 1,
    },
    {
        id: "accesorio-02",
        titulo: "Truck Buller",
        imagen: "./img/truck02.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "accesorio-03",
        titulo: "Truck Independent",
        imagen: "./img/truck03.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "accesorio-04",
        titulo: "Truck Krux",
        imagen: "./img/truck04.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "accesorio-05",
        titulo: "Rueda Woddoo",
        imagen: "./img/rueda01.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "accesorio-06",
        titulo: "Rueda Woddoo",
        imagen: "./img/rueda02.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "accesorio-07",
        titulo: "Tabla Santa Cruz",
        imagen: "./img/tablasantacruz.jpg",
       precio: 1000,
        cantidad: 1,
    },
    {
        id: "accesorio-08",
        titulo: "Tabla Creature",
        imagen: "./img/tablacreature.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "accesorio-09",
        titulo: "Lija MOB",
        imagen: "./img/lija01.jpg",
       precio: 1000,
        cantidad: 1,
    },
    {
        id: "accesorio-10",
        titulo: "Lija Buller",
        imagen: "./img/lija02.jpg",
        precio: 1000,
        cantidad: 1,
    },
    {
        id: "accesorio-11",
        titulo: "Tornillos Independt",
        imagen: "./img/tornillos01.jpg",
       precio: 1000,
        cantidad: 1,
    },  
    {
        id: "accesorio-11",
        titulo: "Tornillos Independt",
        imagen: "./img/rulemanes.jpg",
        precio: 1000,
        cantidad: 1,
    },  

];
